### ISSUE TITLE
Should rerunning the task report previous failures?

### ISSUE THREAD

**Issue by ouchadam** [novoda/gradle-static-analysis-plugin#11] opened 2016-12-13 11:43 UTC
Given a previously failed result, when running the task again the build does not fail. 

Should we consider this expected?

**Comment by mr-archano** [comment] 2016-12-15 16:21
@ouchadam I'm not sure I understanding what you're asking. To clarify: the build will fail **iff** the thresholds are violated. Running the same task again on the same sources should lead to the same result. Do you have a sample where we can reproduce this issue?

**Comment by ouchadam** [comment] 2017-01-10 10:54
The static analysis task had cached it's result which meant it was skipped the second time the build was ran. This meant the build passed even though there were violations.

**Comment by mr-archano** [comment] 2017-01-10 12:54
OH. That's nasty. I would say this behaviour is probably inherited from one of the static analysis tools integrated (findbugs?) but we can try to workaround it once we create our tasks.
to be investigated (I'll add it to our backlog).

**Comment by mr-archano** [comment] 2017-02-24 13:03
I tried this with different setups but couldn't reproduce. Closing the issue for now. @ouchadam if you encounter this issue again please let me know.

**Comment by mr-archano** [comment] 2017-02-24 13:08
I talked too early: it seems I found a project where I can reproduce this. I will share more info shortly. Reopening for now.

**Comment by mr-archano** [comment] 2017-02-24 17:28
I could reproduce the issue easily using an integration test. The problem seems related to the fact the violations are now collected only if static analysis tasks (eg: `checkstyleMain`) are run. When one of these tasks is `UP-TO-DATE` because inputs are the same then we don't evaluate the reports (already generated) and this yields a wrong result for `evaluateViolations`.
:man_facepalming:
One way of fixing this is to move the collection of violations as separate task that would run always. This could be combined with the feature requested in #18 and lead to better configuration API altogether.

**Comment by mr-archano** [comment] 2017-03-21 05:59
Fixed in #30

**Closed by mr-archano** 2017-03-21 05:59 UTC
Labels: bug
