### ISSUE TITLE
Allow source sets to be included/ignored

### ISSUE THREAD

**Issue by ouchadam** [novoda/gradle-static-analysis-plugin#21] opened 2017-02-06 17:34 UTC
As a user of this plugin I would like to run `evaluateViolations` but only on my main source set (no unit/instrumentation tests or flavours)

**Comment by eduardb** [comment] 2017-02-06 17:38
I would add that for Android modules, have a way to include/exclude variants.

**Comment by mr-archano** [comment] 2017-02-08 17:24
Followed up this with @ouchadam in slack: sourcesets can be already ignored via the `exclude` filters. The problem is related to the fact `evaluateViolations` is a unique task, which depends on all the static analysis task. It's not possible at the moment to specify to check a specific sourceset/variant only (eg: `evaluateViolationsMain` or `evaluateViolationsDebug`).

I'm reluctant to add this feature because I feel will disrupt the evaluation of the thresholds: are those gonna be global values? per variant values? what when we want to include more than one variant then?

@ouchadam @eduardb I'm happy to take a look at the issue that you're facing at the moment and try to understand further.

**Comment by mr-archano** [comment] 2017-02-22 20:04
Fixed in #28

**Closed by mr-archano** 2017-02-22 20:04 UTC
Labels: enhancement
